ignoreScripts: true
minimumReleaseAge: 5760
trustPolicy: no-downgrade
catalogMode: prefer
strictDepBuilds: true
blockExoticSubdeps: true

catalogs:
  dev:
    publint: 0.3.21
    tsdown: 0.22.3
    typescript: 6.0.3
    valibot: 1.4.2
    yaml: 2.9.0
    oxfmt: 0.58.0
    oxlint: 1.67.0
    oxlint-tsgolint: 0.24.0

  types:
    "@types/node": 24.13.2
